src/embedWebFonts.ts

I don't know if anyone created an issue on the repo, but I was able to find this question on SO: https://stackoverflow.com/questions/50977367/htmltoimage-chrome-64-securityerror-failed-to-read-the-cssrules-property-from
If it was already reported, please link it accordingly.
Cheers!

correct check for cssRules property on styleSheets

---

package.json
src/embedWebFonts.ts

I was using this for creating screenshots as part of a feedback plugin on a site and needed to be able to properly render google fonts that were being loaded directly from google so I added this in. 
First time using TypeScript so wouldn't be suprised if I've done some ugly things. Feel free to point them out. Happy to keep this as my own fork if it's something you don't want in your version.

Add ability to inline external web fonts

---

tsconfig.json

When you try get the package with unpkg:
`<script src="https://unpkg.com/html-to-image"></script>
`
You get an error:
`Object.defineProperty(exports, "__esModule", { value: true });
`
Because de Browser does not support exports.

Fix bad build for commonjs

---

src/index.ts

This is a fix for the newly opened issue. https://github.com/bubkoo/html-to-image/issues/59
What I did is, I introduced a variable for pixel ratio and set that pixel ratio or the default pixel ratio of the device. So now developer can set their own pixel ratio or if they did not set that variable in options then it gets the default ratio from the device.

added the pixel ratio to the options

---

src/applyStyleWithOptions.ts
src/embedWebFonts.ts
src/getBlobFromURL.ts
src/index.ts
test/spec/index.spec.ts

It reduces resource downloads such ass CSS and font files.
These changes basically fixes #34 and especially this https://github.com/bubkoo/html-to-image/issues/34#issuecomment-726795254

Avoid downloading same resources while rendering

---

src/embedWebFonts.ts

This ensures `@import` rules are parsed as separate rules from block-style rules.
It fixes the problem with Adobe Fonts/Typekit outlined in #96. Fonts from that source have an `@import` rule that hits some analytics URL which returns a stylesheet with an empty comment. `html-to-image` already transforms the URL into a data URI but the regex for parsing the CSS is too greedy and captures both the `@import` rule and any following block-style rule as one rule.
The fix includes 1 refactor of a regular expression into literal syntax. The other regular expressions could probably be refactored this way too but I didn't want to mess around with them too much as they are constructed in a different place from where they are written. The benefits are fairly obvious, but to summarise:
* No need for …

fix: 🐛 parse @import rules in fetched CSS

---

src/embedImages.ts
src/embedResources.ts
src/getBlobFromURL.ts

- Modify getBlobFromURL to return the blob and the contentType
- Modify embedImages and embedResources to use the contentType provided by getBlobFromUrl to get the mime type of the file if source's extension is not provided.
There are cases when the URL provided the img element does not contain the extension. This cause the conversion of the blob to the dataUrl failed, because the mime type returned from `getMimeType(node.src)` will be an empty string. In this scenario, the type can be retrieved from the Content-Type header response after fetching the resource.

fix: 🐛 use content-type to get image src type if extension is not provided in url

---

README.md
src/embedResources.ts
src/embedWebFonts.ts
src/index.ts
test/spec/helper.ts
test/spec/index.spec.ts

This new feature adds a string option called `preferredFontFormat`. When the option is specified, all font formats that do not match the string given are not embedded in the resulting CSS. 
Unlike Google Fonts, Adobe Fonts/TypeKit does not perform any browser detection before serving up its CSS files. This means it has to define each font format in a single `src` property, like this:
```css
src: url("...") format("woff2"), url("...") format ("woff"), url("...") format("opentype");
```
This results in each variant (normal, different weights, italic, etc) being downloaded 3 times—one per format in this case. It's wasteful and, if the library functions are called multiple times, it can add up to a lot of time wasted. In our case, calling `.toCanvas()` 13 times on separate HTML elements took …

feat: ✨ option to specify preferred font format

---

README.md
src/embedWebFonts.ts
src/index.ts
test/spec/index.spec.ts

This builds on the [previous optimisation](https://github.com/bubkoo/html-to-image/pull/106) that lets you specify `preferredFontFormat` with another new option: `fontEmbedCss`. When this option is supplied, the majority of the font embedding process is skipped and only the supplied CSS is used.
To compliment the option a new exported method, `getFontEmbedCss(node, options)`, will run the majority of the process.
When calling the library multiple times for different elements, the embed code is run each time. This is where most of the execution time is spent when snapshotting elements on pages with webfonts. This change allows you to do the heavy lifting up front a single time so that the snapshotting process is much faster. In our testing, this further reduced time spent snapshotting 13 …

feat: ✨ option to specify font embed css

---

src/index.ts

Adding options canvasWidth and canvasHeight to control
size of the exported image, without having to resize the source
node element.
Adding canvasWidth and canvasHeight to options.
If specified, use canvasWidth and canvasHeight when setting canvas.width and canvas.height.
If not specified, default to width/height from getImagesize()
Need to control the resolution of the exported canvas.
Setting options.width or options.height doesn't scale the underlying text and elements within the domNode. 
With this change, the exported canvas width/height can be controlled and scaled.

feat(tocanvas): ✨ adding custom width/height for exported canvas

---

src/util.ts

Overflowing child elements cause unnecessary empty padding around the rendered image because scrollWidth/Height calculate the node's width/height including all the overflowing elements
Change scrollWidth/scrollHeight to clientWidth/clientHeight
It fixed the issue mentioned here (by me) : [Issue 126](https://github.com/bubkoo/html-to-image/issues/126)

Replace scrollWidth/Height with clientWidth/Height

---

src/createSvgDataURL.ts
test/spec/index.spec.ts

Adds a [viewBox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) attribute to rendered SVGs. 
This change just sets the `viewBox` to match the `width` and `height` attributes that are already being set on the SVG, so the image isn't visually altered by this change. Example:
```
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="9" viewBox="0 0 100 9">
```
Having a `viewBox` set helps with allowing a browser to auto-scale the SVG when it's displayed inside a parent container (for example, a `<div>` wrapper of a different size than the image).
The `should render content from shadow node of custom element` test is failing in `master`, so this change doesn't address that.

feat: ✨ Add viewBox attribute to SVG

---

src/cloneNode.ts

Need to handle `slot.assignedNodes` in `cloneNode.ts`
This change is required because slot nodes currently are skipped.
https://github.com/bubkoo/html-to-image/issues/164
`should render content from shadow node of custom element` is failing even though the base64 strings are identical... I am not familiar with this style of test-bed and your helper impl's so it was difficult for me to identify the issue... I am also on `WSL` so it is very plausible that this is only an issue on my local dev environment.

fix: 🐛 ternary to convert slot assignedNodes to array

---

src/embedWebFonts.ts
src/getBlobFromURL.ts
src/options.ts

the `fetch` used in html-to-image should be config. because when image are cross origin , we should use fetch like this:
```
window.fetch(url, { credentials: 'include' } )
```

feat: add 'fetchRequestInit' option

---

src/embedResources.ts

Use `document.styleSheets[index].cssRules[0].cssText` to get font-face, (index is dependent on styleSheets load order)
On windows,
```
@font-face { font-family: "Material Design Icons"; src: url("https://cdn.jsdelivr.net/npm/@mdi/font@6.5.95/fonts/materialdesignicons-webfont.woff2?v=6.5.95") format("woff2"), url("https://cdn.jsdelivr.net/npm/@mdi/font@6.5.95/fonts/materialdesignicons-webfont.ttf?v=6.5.95") format("truetype"); font-weight: normal; font-style: normal; }
```
But when using Safari on iOS or Safari/Chrome on iPhone, 
```
@font-face { font-family: "Material Design Icons"; src: url(https://cdn.jsdelivr.net/npm/@mdi/font@6.5.95/fonts/materialdesignicons-webfont.woff2?v=6.5.95) format(woff2), url(https://cdn.jsdelivr.net/npm/@mdi/font@6.5.95/fonts/materialdesignicons-webfont.ttf?v= …
```

fix: 🐛 font format could be without qoutation

---

src/cloneNode.ts

Set `selected` attribute on the option with a value that corresponds to the value of the select tag.
Problem as described in issue https://github.com/bubkoo/html-to-image/issues/277
The value of select tags is not stored in the html and are thus lost in the `clonedNode`.
Setting the `selected` attribute on the option ensures that it is preserved in the final image.

fix: 🐛  selected option not preserved in image

---

src/cloneNode.ts

Reduced font-size for elements because text don't fit in the blocks.
Decimal font size in CSS and font-size in SVG are different.
#132
In SVG, when text is scaled up or down, browsers calculate the final size of the text (which is determined by the specified font size and the applied scale) and request a font of that computed size from the platform's font system. But if you request a font size of, say, 9 with a scale of 140%, the resulting font size of 12.6 doesn't explicitly exist in the font system, so the browser rounds the font size to 12 instead. This results in stair-step scaling of text.
Issue #132
Reduce font-size in clone styles method
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [ x] I have read the …

fix: 🐛 text breaks on the last word

---

src/cloneNode.ts

Safari `cssText` does not include transform-origin prop
The only change was to copy transform-origin prop additionally with copying the cssText from source to target node
Problem was described in issue https://github.com/bubkoo/html-to-image/issues/296

fix: 🐛 cloneCSSStyle: copy transformOriginProp

---

.eslintrc
README.md
src/embedWebFonts.ts
src/getBlobFromURL.ts
src/options.ts

Gives the option to use the entire URL in order to have a cache key that includes query parameters.
Fixes: https://github.com/bubkoo/html-to-image/issues/259

feat: ✨ added includeQueryParams flag

---

README.md
src/embed-images.ts
src/util.ts

We have found & fix this issue in Safari: https://github.com/GoogleForCreators/web-stories-wp/issues/12432
`decode()` [support](https://caniuse.com/mdn-api_htmlimageelement_decode) is great so we probably don't need a fallback, but I'm happy to hear your thoughts.
Also, I think the readme should be updated because it works pretty well in Safari.

Fix Safari images

---

src/clone-node.ts

This pull request addresses the issue with capturing videos and iframes in the library, where the resulting images were blank or incorrect.
To fix this issue, I have updated the `cloneVideoElement` and `cloneIframeElement` functions to use the `contentDocument.body` and `canvas` APIs to capture frames from the videos and iframes, and convert them to data URLs.
For videos, I have added a `canvas` element to the page, set its size to the same size as the video, and used the `drawImage` method to draw the video to the canvas. I have then used the `canvas.toDataURL` method to convert the canvas image to a data URL.
For iframes, I have used the `contentDocument` property of the `HTMLIFrameElement` to access the `document` object of the iframe, and then used the `querySelector` method to find …

fix: use frames for video capture & add iframes

---

package.json

I added "src" in the files attribute of package.json
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Chore (changes that don't modify src or test files)

fix: include source in npm package

---

src/embed-images.ts

I noticed an issue with my images not loading. I traced it to neither `onload` or `onerror` firing during the `embedImageNode` step, which I was able to fix by changing the `loading` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading) attribute to `eager` instead of `lazy` as my images are.
Add a condition during `embedImageNode` that changes lazy loading images to eager to ensure (ideally) that onload/onerror fires.
This problem occurs at least for me when I have an `img` which has `loading` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading) set to `lazy`. Changing this to `eager` stops the problem, so I've made this adjustment occur during cloning as we would not want to lazy loading images when we are trying to clone them and are …

fix: switch lazy loading images to eager

---

src/clone-node.ts

There is a difference between values in actual d attribute of path and value that returns from window.getComputedStyles() object For some generated svg shapes at particular place is crutial to have exact values in order them to be displayed at all.
Closes #357
There is a problem appears for `path` elements with precise values in `d` attribute on cloneCSSStyle step.
`window.getComputedStyles() ` which is used to get styles to apply them on cloned element returns rounded values
which is wrong for some elements.
For e.g here I'm inspecting cloned element and the elements are actually present but because of rounded values after styles were copied they are invisible with height 0 and width 0:

fix(cloneCSSStyle): rounded values of d attribute fix

---

src/util.ts

`img.decode = () => resolve(img);` is supposed to ensure that the image is fully processed but is misused. Decode is not a setter, it's a method that returns a promise when the image is fully decoded. While this code wait for the image to load it does not wait for it to be fully ready (processed).
`img.decode()` ensures that the image has been fully decoded before continuing.
We go one step further with `requestAnimationFrame`. This defers the execution and will ensure that the resolved image is rendered in the next frame. It's more important in devices like Ipad because the broswers tend to handle image operations differently, thus creating rendering and timing issues.
Images were not rendered when printing documents which have images on ipad. But is is working fine outside IOS.
IOS has …

fix: ensure images are totally prcoessed before using them (ios)

---

src/clone-node.ts

Optimize cloning of SVG elements
Instead of cloning each child SVG element (which in my case is around 200) we can use cloneNode(true) to use deep clone mode
Converting DIV with SVG inside taking around 20 second in Safari and around 15 in Chrome
- [x ] Enhancement (changes that improvement of current feature or performance)
- [x ] My code follows the code style of this project.

perf: svg cloning optimized using deep clone

---

README.md

Change `fontEmbedCss` to `fontEmbedCSS` in the doc because the option name is `fontEmbedCSS`.

docs: fix typo fontEmbedCss -> fontEmbedCSS

---

src/embed-webfonts.ts
test/resources/fonts/web-fonts/empty.html
test/spec/webfont.spec.ts

Optimized by embedding only the fonts that are actually used.
The document may have many fonts that are not used by the nodes to be processed. Currently, all fonts are embedded.
Added an optimization that recursively traverses the nodes to find the fonts that are used, then filters out the fonts that are not used before embedding them.
This can significantly reduce processing time and the size of the SVG.
Resolves #405, resolves #389, resolves #310

perf: embed only used fonts

---

src/embed-webfonts.ts

Fixes the handling of font css when cssRules are inaccessible.
When cssRules are inaccessible in a style sheet, getCSSRules will throw an exception trying to read them, and then the catch handler will fetch the css. But, when it goes to insert the rule, it has a bug where it uses sheet.cssRules.length, which causes an exception again and the rules are lost.
This results in the error:
```
Error inlining remote css file SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
```
This is referenced in a few issues such as issue #49.
This fixes issues when fonts are referenced via external style sheets and the css cannot be read. The resulting image
will be missing the fonts that failed. This error is mentioned in a few issues such as …

Fixes issue fetching font css when cssRules are inaccessilbe

---

src/embed-images.ts

Add support for `mask` and `mask-image` properties for browsers that support them via webkit.

fix(mask): add support for -webkit-mask and -webkit-mask-image
